#!/usr/bin/env bash
# Change the current wallpaper.

# Directory where wallpapers are stored. The file stored in this directory
# which matches $wallpaper_directory/wallpaper.* is the currently set wallpaper
# if set with -i argument.
wallpaper_directory=$HOME/.config/wallpaper

setwall() {
	# Set wallpaper with feh, if it exists.
	command -v feh >/dev/null 2>&1 &&
		feh --bg-fill "$1"
	# Generate scheme from wallpaper with wal and pywalfox, if they exist.
	command -v wal >/dev/null 2>&1 &&
		wal -c &&
		wal -qsni "$1" --saturate 0.5 --backend haishoku &&
		command -v pywalfox >/dev/null 2>&1 &&
		pywalfox update
}

list() {
	# List available wallpapers.
	for f in "$wallpaper_directory"/*; do
		file="${f##*/}"
		case $file in
		wallpaper.*) ;;
		*) echo "$file" ;;
		esac
	done
}

change() {
	# Remove old wallpaper and replace it with new wallpaper.
	old_wallpaper=("$wallpaper_directory"/wallpaper.*)
	rm -f "${old_wallpaper[@]}"
	new_wallpaper=$1
	cp "$wallpaper_directory"/"$new_wallpaper" \
		"$wallpaper_directory"/wallpaper."${new_wallpaper##*.}"
}

usage() {
	printf "%s" "\
USAGE:
    changewall [FLAGS] [IMAGE]

FLAGS:
    -i image     Sets wallpaper to image from directory
    -l, --list   Lists all available wallpapers
    -h, --help   Prints help information
"
}

case "$1" in
"-i")
	change "$2" && setwall "$wallpaper_directory"/wallpaper.*
	;;
"-l" | "--list")
	list
	;;
"-h" | "--help")
	usage
	exit 0
	;;
"")
	# Default.
	setwall "$wallpaper_directory"/wallpaper.*
	;;
*)
	setwall "$1"
	;;
esac
