#!/usr/bin/env bash
# Change the current wallpaper.
# Calls upon a script named `setwall` to set the wallpaper.

shopt -s extglob

wallpaper_directory="$HOME/.config/wallpaper"

list() {
	# List available wallpapers.
	wallpapers=$(ls "$wallpaper_directory")
	for wallpaper in $wallpapers; do
		# Do not include current wallpaper file.
		if [[ $wallpaper != wallpaper.* ]]; then
			echo "$wallpaper"
		fi
	done
}

change() {
	new_wallpaper="$1"
	old_wallpapers=("$wallpaper_directory/wallpaper".*)
	old_wallpaper="${old_wallpapers[0]}"
	# Remove old wallpaper.
	if [[ -f $old_wallpaper ]]; then
		rm "$old_wallpaper"
	fi

	# Replace wallpaper
	cp "$wallpaper_directory"/"$new_wallpaper" "$wallpaper_directory"/wallpaper."${new_wallpaper##*.}"

	# Execute external script which should set the wallpaper.
	exec setwall
}

usage() {
	printf "%s" "\
USAGE:
    changewall [FLAGS]

FLAGS:
    -i image     Sets wallpaper to image
    -l, --list   Lists all available wallpapers
    -h, --help   Prints help information
"
	exit 1
}

case "$1" in
"-l" | "--list")
	list
	;;
"-i")
	change "$2"
	;;
*)
	usage
	;;
esac
