#!/usr/bin/env bash
# Query all clean git directories in current directory

for d in *; do
	if [ -d "$d/.git" ] && [ -z "$(git --git-dir="$d/.git" --work-tree="$d" status --porcelain)" ]; then
		echo "$d"
	fi
done
