#!/usr/bin/env bash
# ssh into rpi and output GPU and CPU temperature

ssh rpi '
echo "$(hostname) temperature:";
gpu=$(vcgencmd measure_temp | cut -c 6-);
echo "GPU => $gpu";
cpu=$(</sys/class/thermal/thermal_zone0/temp);
echo "CPU => $((cpu/1000))'"'"'C";
'
