#!/usr/bin/env bash
# Change current wallpaper to ~/.config/wallpaper/wallpaper.* using feh

WALLPAPER="$HOME"/.config/wallpaper/wallpaper.*

feh --bg-fill $WALLPAPER
wal -c
wal -qsi $WALLPAPER
pywalfox update
