#!/bin/sh

# Separator displayed between two modules.
separator="|"

disk() {
	df -h / | awk ' /[0-9]/ {print $3 "/" $2}'
}

packages() {
	echo "$(pacman -Q | wc -l) pkgs"
}

sptstatus() {
	spt playback -f "%v% %s"
}

datetime() {
	date +"%a %d %b %I:%M %p"
}

bar() {
	module disk
	module packages
	module sptstatus
	module datetime
}

module() {
	# Only echoes if the command succeeds.
	out=$($1 2>&1) && echo "$out"
}

while :; do
	xsetroot -name " $(bar | xargs -d "\n" printf "%s\n$separator\n" | head -n -1 | tr "\n" " ")"
	sleep 3s
done
