name: xmonad-config

dependencies:
  - base
  - containers
  - unix
  - X11
  - xmonad >= 0.17
  - xmonad-contrib >= 0.17

library:
  source-dirs: src

executables:
  xmonad:
    source-dirs: app
    other-modules: []
    main: Main.hs
    dependencies: xmonad-config
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
