#!/bin/sh

killall sxhkd; sxhkd &
killall compton; compton &
feh --bg-fill ~/.config/wallpaper/wallpaper.*
xsetroot -cursor_name arrow
~/.config/polybar/launch.sh

xrandr --output HDMI-1 --left-of DVI-D-1
bspc monitor 0x00200002 -n "A" -d 1/{a,b,c}
bspc monitor 0x00200004 -n "B" -d 2/{a,b,c}

bspc config border_width          1
bspc config window_gap            15

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

bspc config focused_border_color  \#e7c547

bspc rule -a Zathura state=tiled
