#!/bin/sh

killall sxhkd; sxhkd &
killall compton; compton &
feh --bg-fill ~/.config/wallpaper/wallpaper.*
xsetroot -cursor_name arrow
xinput --set-prop 12 "libinput Accel Speed" -0.5
~/.config/polybar/launch.sh

xrandr --output HDMI-0 --left-of DVI-D-0
bspc monitor DVI-D-0 -n "A" -d 1 2
bspc monitor HDMI-0 -n "B" -d 3 4

bspc config border_width          1
bspc config window_gap            15

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

bspc config focused_border_color  \#e7c547

bspc rule -a Zathura state=tiled
