#!/bin/sh

killall sxhkd; sxhkd &

# Launch polybar with bspwm arguments for workspace view
~/.config/polybar/launch.sh bspwm

bspc monitor DP-2 -d 1 2
bspc monitor DVI-D-0 -d 3 4
bspc monitor HDMI-0 -d 5 6

bspc config border_width          3
bspc config window_gap            15

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

bspc config focused_border_color  "#fafafa"

bspc rule -a Zathura state=tiled

# Startup script
exec startup
