#!/bin/sh

"$HOME"/.config/polybar/launch.sh

xres() {
	xrdb -query | grep "$1" | cut -f2
}

pgrep -x sxhkd >/dev/null || sxhkd &

for monitor in $(bspc query -M); do
	bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9
done

bspc config border_width 1
bspc config normal_border_color "$(xres "*.background")"
bspc config focused_border_color "$(xres "*.foreground")"
bspc config presel_feedback_color "$(xres "*.color4")"
bspc config window_gap 15

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled
bspc config external_rules_command "$HOME"/bin/bspwmexternal

exec startup
