# Config file for spotify-tui

behavior:
    playing_icon: ▶
    paused_icon: ⏸
    show_loading_indicator: false

keybindings:
    increase_volume: "="

theme:
    active: "242, 151, 24"
    banner: White
    hovered: "242, 151, 24"
    inactive: Gray
    playbar_background: Black
    playbar_progress: "242, 151, 24"
    playbar_progress_text: White
    selected: "255, 51, 51"
    text: "255, 255, 255"
    header: "242, 151, 24"
